### PR TITLE
Edu Portal Issue Solved

### PR DESCRIPTION
**Pull request by yogeshmadaan100**
#2 Issue has been resolved. Please review :)

### CODE REVIEW

**Comment by tarun550** [comment]
Can you explain how did you fix the issue with this?
The URLs were already present in the in the original APK

**Comment by yogeshmadaan100** [comment]
Firstly I reversed engineered the apk to get the sample url.. And in
respect to specific issue i entered the limit parameter that was missing in
edu activity. And as a result default parameter 0 was taken and same set of
result is returned on load more.

**Comment by yogeshmadaan100** [comment]
Hello tarun,

Just saw the updated desciption.. Was not aware of the security issue. I
can remove the url if you want .... And then ask for a merge request.

Waiting for your response

**Comment by yogeshmadaan100** [comment]
@tarun550 @thehitechpanky   Kindly Check it Now. Code Cleaned :) Easy to merge.

**Pull request merged**
